project:
  type: website
  output-dir: docs

website:
  title: "Robert-Gulmann"
  favicon: images/Favicon-Logo.png
  navbar:
    title: false
    logo: images/Nav-Bar-Logo.png
    left:
      - href: "#about"
        text: About
      - href: "#projects"
        text: Projects
      - href: "#media"
        text: Media
      - href: "#contact"
        text: Contact
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/robert-gulmann/"
        target: _blank
      - icon: github
        href: "https://github.com/robert-gulmann/"
        target: _blank
      - icon: envelope
        href: "mailto:robert.gulmann3@mail.dcu.ie"
format:
  html:
    theme:
      - lux
      - style.scss
    toc: false
    page-layout: full
    mainfont: Poppins