project:
  type: website
  output-dir: docs

website:
  title: "Robert-Gulmann"
  favicon: images/RG_Logo.png
  navbar:
    title: false
    logo: images/RG_Logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: media.qmd
        text: Media
      - href: hello.qmd
        text: Hello
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: 
      - lux  # Base theme
      - style.scss  # Custom styles
    toc: false
    page-layout: full
    mainfont: Poppins  # Apply the Google Font globally